/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as DomainsRouteImport } from './routes/domains'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as DomainsIndexRouteImport } from './routes/domains/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as DomainsDomainNameRouteImport } from './routes/domains/$domainName'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as ProjectsProjectIdEnvironmentRouteImport } from './routes/projects/$projectId/environment'
import { Route as ProjectsProjectIdDomainsRouteImport } from './routes/projects/$projectId/domains'
import { Route as ProjectsProjectIdDeploymentHistoryRouteImport } from './routes/projects/$projectId/deployment-history'
import { Route as ProjectsProjectIdConfigurationRouteImport } from './routes/projects/$projectId/configuration'
import { Route as ProjectsProjectIdDomainsIndexRouteImport } from './routes/projects/$projectId/domains/index'
import { Route as ProjectsProjectIdDomainsDomainNameRouteImport } from './routes/projects/$projectId/domains/$domainName'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsRoute = DomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const DomainsIndexRoute = DomainsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DomainsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const DomainsDomainNameRoute = DomainsDomainNameRouteImport.update({
  id: '/$domainName',
  path: '/$domainName',
  getParentRoute: () => DomainsRoute,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdEnvironmentRoute =
  ProjectsProjectIdEnvironmentRouteImport.update({
    id: '/environment',
    path: '/environment',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdDomainsRoute =
  ProjectsProjectIdDomainsRouteImport.update({
    id: '/domains',
    path: '/domains',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdDeploymentHistoryRoute =
  ProjectsProjectIdDeploymentHistoryRouteImport.update({
    id: '/deployment-history',
    path: '/deployment-history',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdConfigurationRoute =
  ProjectsProjectIdConfigurationRouteImport.update({
    id: '/configuration',
    path: '/configuration',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdDomainsIndexRoute =
  ProjectsProjectIdDomainsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectIdDomainsRoute,
  } as any)
const ProjectsProjectIdDomainsDomainNameRoute =
  ProjectsProjectIdDomainsDomainNameRouteImport.update({
    id: '/$domainName',
    path: '/$domainName',
    getParentRoute: () => ProjectsProjectIdDomainsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/domains': typeof DomainsRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/domains/$domainName': typeof DomainsDomainNameRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/domains/': typeof DomainsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/configuration': typeof ProjectsProjectIdConfigurationRoute
  '/projects/$projectId/deployment-history': typeof ProjectsProjectIdDeploymentHistoryRoute
  '/projects/$projectId/domains': typeof ProjectsProjectIdDomainsRouteWithChildren
  '/projects/$projectId/environment': typeof ProjectsProjectIdEnvironmentRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/domains/$domainName': typeof ProjectsProjectIdDomainsDomainNameRoute
  '/projects/$projectId/domains/': typeof ProjectsProjectIdDomainsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/domains/$domainName': typeof DomainsDomainNameRoute
  '/domains': typeof DomainsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/configuration': typeof ProjectsProjectIdConfigurationRoute
  '/projects/$projectId/deployment-history': typeof ProjectsProjectIdDeploymentHistoryRoute
  '/projects/$projectId/environment': typeof ProjectsProjectIdEnvironmentRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/domains/$domainName': typeof ProjectsProjectIdDomainsDomainNameRoute
  '/projects/$projectId/domains': typeof ProjectsProjectIdDomainsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/domains': typeof DomainsRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/domains/$domainName': typeof DomainsDomainNameRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/domains/': typeof DomainsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/configuration': typeof ProjectsProjectIdConfigurationRoute
  '/projects/$projectId/deployment-history': typeof ProjectsProjectIdDeploymentHistoryRoute
  '/projects/$projectId/domains': typeof ProjectsProjectIdDomainsRouteWithChildren
  '/projects/$projectId/environment': typeof ProjectsProjectIdEnvironmentRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/domains/$domainName': typeof ProjectsProjectIdDomainsDomainNameRoute
  '/projects/$projectId/domains/': typeof ProjectsProjectIdDomainsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/domains'
    | '/projects'
    | '/domains/$domainName'
    | '/projects/$projectId'
    | '/domains/'
    | '/projects/'
    | '/projects/$projectId/configuration'
    | '/projects/$projectId/deployment-history'
    | '/projects/$projectId/domains'
    | '/projects/$projectId/environment'
    | '/projects/$projectId/'
    | '/projects/$projectId/domains/$domainName'
    | '/projects/$projectId/domains/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/domains/$domainName'
    | '/domains'
    | '/projects'
    | '/projects/$projectId/configuration'
    | '/projects/$projectId/deployment-history'
    | '/projects/$projectId/environment'
    | '/projects/$projectId'
    | '/projects/$projectId/domains/$domainName'
    | '/projects/$projectId/domains'
  id:
    | '__root__'
    | '/'
    | '/domains'
    | '/projects'
    | '/domains/$domainName'
    | '/projects/$projectId'
    | '/domains/'
    | '/projects/'
    | '/projects/$projectId/configuration'
    | '/projects/$projectId/deployment-history'
    | '/projects/$projectId/domains'
    | '/projects/$projectId/environment'
    | '/projects/$projectId/'
    | '/projects/$projectId/domains/$domainName'
    | '/projects/$projectId/domains/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DomainsRoute: typeof DomainsRouteWithChildren
  ProjectsRoute: typeof ProjectsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains': {
      id: '/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/domains/': {
      id: '/domains/'
      path: '/'
      fullPath: '/domains/'
      preLoaderRoute: typeof DomainsIndexRouteImport
      parentRoute: typeof DomainsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/domains/$domainName': {
      id: '/domains/$domainName'
      path: '/$domainName'
      fullPath: '/domains/$domainName'
      preLoaderRoute: typeof DomainsDomainNameRouteImport
      parentRoute: typeof DomainsRoute
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/environment': {
      id: '/projects/$projectId/environment'
      path: '/environment'
      fullPath: '/projects/$projectId/environment'
      preLoaderRoute: typeof ProjectsProjectIdEnvironmentRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/domains': {
      id: '/projects/$projectId/domains'
      path: '/domains'
      fullPath: '/projects/$projectId/domains'
      preLoaderRoute: typeof ProjectsProjectIdDomainsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/deployment-history': {
      id: '/projects/$projectId/deployment-history'
      path: '/deployment-history'
      fullPath: '/projects/$projectId/deployment-history'
      preLoaderRoute: typeof ProjectsProjectIdDeploymentHistoryRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/configuration': {
      id: '/projects/$projectId/configuration'
      path: '/configuration'
      fullPath: '/projects/$projectId/configuration'
      preLoaderRoute: typeof ProjectsProjectIdConfigurationRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/domains/': {
      id: '/projects/$projectId/domains/'
      path: '/'
      fullPath: '/projects/$projectId/domains/'
      preLoaderRoute: typeof ProjectsProjectIdDomainsIndexRouteImport
      parentRoute: typeof ProjectsProjectIdDomainsRoute
    }
    '/projects/$projectId/domains/$domainName': {
      id: '/projects/$projectId/domains/$domainName'
      path: '/$domainName'
      fullPath: '/projects/$projectId/domains/$domainName'
      preLoaderRoute: typeof ProjectsProjectIdDomainsDomainNameRouteImport
      parentRoute: typeof ProjectsProjectIdDomainsRoute
    }
  }
}

interface DomainsRouteChildren {
  DomainsDomainNameRoute: typeof DomainsDomainNameRoute
  DomainsIndexRoute: typeof DomainsIndexRoute
}

const DomainsRouteChildren: DomainsRouteChildren = {
  DomainsDomainNameRoute: DomainsDomainNameRoute,
  DomainsIndexRoute: DomainsIndexRoute,
}

const DomainsRouteWithChildren =
  DomainsRoute._addFileChildren(DomainsRouteChildren)

interface ProjectsProjectIdDomainsRouteChildren {
  ProjectsProjectIdDomainsDomainNameRoute: typeof ProjectsProjectIdDomainsDomainNameRoute
  ProjectsProjectIdDomainsIndexRoute: typeof ProjectsProjectIdDomainsIndexRoute
}

const ProjectsProjectIdDomainsRouteChildren: ProjectsProjectIdDomainsRouteChildren =
  {
    ProjectsProjectIdDomainsDomainNameRoute:
      ProjectsProjectIdDomainsDomainNameRoute,
    ProjectsProjectIdDomainsIndexRoute: ProjectsProjectIdDomainsIndexRoute,
  }

const ProjectsProjectIdDomainsRouteWithChildren =
  ProjectsProjectIdDomainsRoute._addFileChildren(
    ProjectsProjectIdDomainsRouteChildren,
  )

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdConfigurationRoute: typeof ProjectsProjectIdConfigurationRoute
  ProjectsProjectIdDeploymentHistoryRoute: typeof ProjectsProjectIdDeploymentHistoryRoute
  ProjectsProjectIdDomainsRoute: typeof ProjectsProjectIdDomainsRouteWithChildren
  ProjectsProjectIdEnvironmentRoute: typeof ProjectsProjectIdEnvironmentRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdConfigurationRoute: ProjectsProjectIdConfigurationRoute,
  ProjectsProjectIdDeploymentHistoryRoute:
    ProjectsProjectIdDeploymentHistoryRoute,
  ProjectsProjectIdDomainsRoute: ProjectsProjectIdDomainsRouteWithChildren,
  ProjectsProjectIdEnvironmentRoute: ProjectsProjectIdEnvironmentRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DomainsRoute: DomainsRouteWithChildren,
  ProjectsRoute: ProjectsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
